const ABUSE_REASONS = {
    PREV_EDIT: 'EDITING A PREVIOUSLY SENT MESSAGE TO INCLUDE AN "ARGL"',
    SELF_REPLY: '"ARGL"ING THEIR OWN MESSAGE',
    OWN_NAME_CHANGE: '"ARGL"ING THEIR OWN NAME CHANGE'
};

export default ABUSE_REASONS;
